name: Run and Output bash file

on:
    push:
        branches:
            - master
            - main


jobs:
    run-script:
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout-repository
                uses: actions/checkout@v4
            
            -   name: Make script Executable
                run: chmod +x hw.sh

            -   name: Run script
                run: ./hw.sh
            
            -   name: Output Content of new file
                run: cat hello.txt
            
